In [13]:
import pandas as pd

# Load the dataset
df = pd.read_csv('fuel.csv')


# Drop rows with NaN values across all columns
# Drop rows with NaN values only if they have less than a certain number of non-NaN values
df.dropna(thresh=3, inplace=True)  # Adjust '3' as needed


# Verify the changes
df.head()

C:\Users\eddum\AppData\Local\Temp\ipykernel_19796\2679980802.py:4: DtypeWarning: Columns (7,44) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('fuel.csv')

,vehicle_id,year,make,model,class,drive,transmission,transmission_type,engine_index,engine_descriptor,...,hours_to_charge_ac_240v,composite_city_mpg,composite_highway_mpg,composite_combined_mpg,range_ft1,city_range_ft1,highway_range_ft1,range_ft2,city_range_ft2,highway_range_ft2
0,26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,NaN,9001,(FFS),...,0.0,0,0,0,0,0.0,0.0,NaN,0.0,0.0
1,27705,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,NaN,9005,(FFS) CA model,...,0.0,0,0,0,0,0.0,0.0,NaN,0.0,0.0
2,26561,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,NaN,9002,(FFS),...,0.0,0,0,0,0,0.0,0.0,NaN,0.0,0.0
3,27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,NaN,9006,(FFS) CA model,...,0.0,0,0,0,0,0.0,0.0,NaN,0.0,0.0
4,27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,NaN,1830,(FFS),...,0.0,0,0,0,0,0.0,0.0,NaN,0.0,0.0

In [6]:
# Check for missing values
missing_values = df.isnull().sum()
print("Missing Values:\n", missing_values)

# Drop rows with missing values
df = df.dropna()

# Check for duplicate rows
duplicate_rows = df.duplicated().sum()
print("\nDuplicate Rows:", duplicate_rows)

# Drop duplicate rows
df = df.drop_duplicates()

# Reset the index
df = df.reset_index(drop=True)

# Display the cleaned dataframe
df.head()

Missing Values:
 vehicle_id               0
year                     0
make                     0
model                    0
class                    0
                     ...
city_range_ft1           0
highway_range_ft1        0
range_ft2            38113
city_range_ft2           0
highway_range_ft2        0
Length: 81, dtype: int64

Duplicate Rows: 0

Empty DataFrame
Columns: [vehicle_id, year, make, model, class, drive, transmission, transmission_type, engine_index, engine_descriptor, engine_cylinders, engine_displacement, turbocharger, supercharger, fuel_type, fuel_type_1, fuel_type_2, city_mpg_ft1, unrounded_city_mpg_ft1, city_mpg_ft2, unrounded_city_mpg_ft2, city_gasoline_consumption_cd, city_electricity_consumption, city_utility_factor, highway_mpg_ft1, unrounded_highway_mpg_ft1, highway_mpg_ft2, unrounded_highway_mpg_ft2, highway_gasoline_consumption_cd, highway_electricity_consumption, highway_utility_factor, unadjusted_city_mpg_ft1, unadjusted_highway_mpg_ft1, unadjusted_city_mpg_ft2, unadjusted_highway_mpg_ft2, combined_mpg_ft1, unrounded_combined_mpg_ft1, combined_mpg_ft2, unrounded_combined_mpg_ft2, combined_electricity_consumption, combined_gasoline_consumption_cd, combined_utility_factor, annual_fuel_cost_ft1, annual_fuel_cost_ft2, gas_guzzler_tax, save_or_spend_5_year, annual_consumption_in_barrels_ft1, annual_consumption_in_barrels_ft2, tailpipe_co2_ft1, tailpipe_co2_in_grams_mile_ft1, tailpipe_co2_ft2, tailpipe_co2_in_grams_mile_ft2, fuel_economy_score, ghg_score, ghg_score_alt_fuel, my_mpg_data, x2d_passenger_volume, x2d_luggage_volume, x4d_passenger_volume, x4d_luggage_volume, hatchback_passenger_volume, hatchback_luggage_volume, start_stop_technology, alternative_fuel_technology, electric_motor, manufacturer_code, gasoline_electricity_blended_cd, vehicle_charger, alternate_charger, hours_to_charge_120v, hours_to_charge_240v, hours_to_charge_ac_240v, composite_city_mpg, composite_highway_mpg, composite_combined_mpg, range_ft1, city_range_ft1, highway_range_ft1, range_ft2, city_range_ft2, highway_range_ft2]
Index: []

[0 rows x 81 columns]

In [8]:
df

Empty DataFrame
Columns: [vehicle_id, year, make, model, class, drive, transmission, transmission_type, engine_index, engine_descriptor, engine_cylinders, engine_displacement, turbocharger, supercharger, fuel_type, fuel_type_1, fuel_type_2, city_mpg_ft1, unrounded_city_mpg_ft1, city_mpg_ft2, unrounded_city_mpg_ft2, city_gasoline_consumption_cd, city_electricity_consumption, city_utility_factor, highway_mpg_ft1, unrounded_highway_mpg_ft1, highway_mpg_ft2, unrounded_highway_mpg_ft2, highway_gasoline_consumption_cd, highway_electricity_consumption, highway_utility_factor, unadjusted_city_mpg_ft1, unadjusted_highway_mpg_ft1, unadjusted_city_mpg_ft2, unadjusted_highway_mpg_ft2, combined_mpg_ft1, unrounded_combined_mpg_ft1, combined_mpg_ft2, unrounded_combined_mpg_ft2, combined_electricity_consumption, combined_gasoline_consumption_cd, combined_utility_factor, annual_fuel_cost_ft1, annual_fuel_cost_ft2, gas_guzzler_tax, save_or_spend_5_year, annual_consumption_in_barrels_ft1, annual_consumption_in_barrels_ft2, tailpipe_co2_ft1, tailpipe_co2_in_grams_mile_ft1, tailpipe_co2_ft2, tailpipe_co2_in_grams_mile_ft2, fuel_economy_score, ghg_score, ghg_score_alt_fuel, my_mpg_data, x2d_passenger_volume, x2d_luggage_volume, x4d_passenger_volume, x4d_luggage_volume, hatchback_passenger_volume, hatchback_luggage_volume, start_stop_technology, alternative_fuel_technology, electric_motor, manufacturer_code, gasoline_electricity_blended_cd, vehicle_charger, alternate_charger, hours_to_charge_120v, hours_to_charge_240v, hours_to_charge_ac_240v, composite_city_mpg, composite_highway_mpg, composite_combined_mpg, range_ft1, city_range_ft1, highway_range_ft1, range_ft2, city_range_ft2, highway_range_ft2]
Index: []

[0 rows x 81 columns]

In [14]:
# Check for columns with all NaN values
all_nan_columns = df.columns[df.isnull().all()]

# Display columns with all NaN values
print("Columns with all NaN values:", all_nan_columns)

Columns with all NaN values: Index(['supercharger', 'fuel_type_2', 'start_stop_technology',
       'electric_motor', 'manufacturer_code', 'vehicle_charger',
       'alternate_charger', 'range_ft2'],
      dtype='object')

In [15]:
# Check the number of columns with all NaN values
num_all_nan_columns = len(all_nan_columns)

# Display the number of columns with all NaN values
print("Number of columns with all NaN values:", num_all_nan_columns)

Number of columns with all NaN values: 8

In [16]:
# Count NaN values for each column
nan_counts = df.isnull().sum()

# Display NaN counts for each column
print("NaN counts for each column:")
print(nan_counts)

NaN counts for each column:
vehicle_id               0
year                     0
make                     0
model                    0
class                    0
                     ...
city_range_ft1           0
highway_range_ft1        0
range_ft2            38113
city_range_ft2           0
highway_range_ft2        0
Length: 81, dtype: int64

In [17]:
# Filter columns with NaN values
nan_columns = nan_counts[nan_counts > 0]

# Display columns with NaN values
print("Columns with NaN values:")
print(nan_columns)

Columns with NaN values:
drive                           1189
transmission                      11
transmission_type              23068
engine_descriptor              15420
engine_cylinders                 136
engine_displacement              134
turbocharger                   32874
supercharger                   38113
fuel_type_2                    38113
gas_guzzler_tax                37149
start_stop_technology          38113
alternative_fuel_technology    35066
electric_motor                 38113
manufacturer_code              38113
vehicle_charger                38113
alternate_charger              38113
range_ft2                      38113
dtype: int64

In [18]:
# Total number of values for each column
total_values_per_column = df.count()

# Display total values for each column
print("Total values for each column:")
print(total_values_per_column)

Total values for each column:
vehicle_id           38113
year                 38113
make                 38113
model                38113
class                38113
                     ...
city_range_ft1       38113
highway_range_ft1    38113
range_ft2                0
city_range_ft2       38113
highway_range_ft2    38113
Length: 81, dtype: int64

In [19]:
# Filter columns with NaN values equal to the total number of rows
columns_to_drop = nan_columns[nan_columns == len(df)]

# Drop columns with all NaN values
df.drop(columns=columns_to_drop.index, inplace=True)

# Write the modified dataframe back to CSV
df.to_csv('cleaned_fuel.csv', index=False)

In [20]:
df

,vehicle_id,year,make,model,class,drive,transmission,transmission_type,engine_index,engine_descriptor,...,hours_to_charge_240v,hours_to_charge_ac_240v,composite_city_mpg,composite_highway_mpg,composite_combined_mpg,range_ft1,city_range_ft1,highway_range_ft1,city_range_ft2,highway_range_ft2
0,26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,NaN,9001,(FFS),...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
1,27705,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,NaN,9005,(FFS) CA model,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
2,26561,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,NaN,9002,(FFS),...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
3,27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,NaN,9006,(FFS) CA model,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
4,27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,NaN,1830,(FFS),...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38108,37564,2017,Volvo,XC60 FWD,Small Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),NaN,90,SIDI,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
38109,37547,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),NaN,52,SIDI,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
38110,37548,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),NaN,53,SIDI,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
38111,37703,2017,Volvo,XC90 AWD PHEV,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),NaN,54,SIDI; PHEV,...,3.0,0.0,29,32,30,0,0.0,0.0,13.84,13.3
38112,37687,2017,Volvo,XC90 FWD,Standard Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),NaN,50,SIDI,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0

In [21]:
# Define threshold for NaN values
threshold = 15000

# Filter columns to drop based on NaN counts
columns_to_drop = nan_columns[(nan_columns > threshold) | (nan_columns.index.isin(['engine_descriptor', 'transmission_type']))]

# Drop columns with more than 15,000 NaN values and 'engine_descriptor', 'transmission_type'
df.drop(columns=columns_to_drop.index, inplace=True)

# Write the modified dataframe back to CSV
df.to_csv('cleaned_fuel.csv', index=False)

KeyError: "['supercharger', 'fuel_type_2', 'start_stop_technology', 'electric_motor', 'manufacturer_code', 'vehicle_charger', 'alternate_charger', 'range_ft2'] not found in axis"

In [ ]:
df

In [22]:
# Define threshold for NaN values
threshold = 15000

# Define columns to drop
columns_to_drop = ['engine_descriptor', 'transmission_type', 'supercharger', 'fuel_type_2', 'start_stop_technology', 'electric_motor', 'manufacturer_code', 'vehicle_charger', 'alternate_charger', 'range_ft2']

# Filter columns to drop based on NaN counts and existence in dataframe
columns_to_drop = [col for col in columns_to_drop if col in df.columns and (nan_counts[col] > threshold)]

# Drop columns with more than 15,000 NaN values and the specified columns
df.drop(columns=columns_to_drop, inplace=True)

# Write the modified dataframe back to CSV
df.to_csv('cleaned_fuel.csv', index=False)

In [23]:
df

,vehicle_id,year,make,model,class,drive,transmission,engine_index,engine_cylinders,engine_displacement,...,hours_to_charge_240v,hours_to_charge_ac_240v,composite_city_mpg,composite_highway_mpg,composite_combined_mpg,range_ft1,city_range_ft1,highway_range_ft1,city_range_ft2,highway_range_ft2
0,26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,9001,6.0,2.5,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
1,27705,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,9005,6.0,2.5,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
2,26561,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,9002,4.0,2.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
3,27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,9006,4.0,2.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
4,27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,1830,4.0,2.5,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38108,37564,2017,Volvo,XC60 FWD,Small Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),90,4.0,2.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
38109,37547,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),52,4.0,2.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
38110,37548,2017,Volvo,XC90 AWD,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),53,4.0,2.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0
38111,37703,2017,Volvo,XC90 AWD PHEV,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),54,4.0,2.0,...,3.0,0.0,29,32,30,0,0.0,0.0,13.84,13.3
38112,37687,2017,Volvo,XC90 FWD,Standard Sport Utility Vehicle 2WD,Front-Wheel Drive,Automatic (S8),50,4.0,2.0,...,0.0,0.0,0,0,0,0,0.0,0.0,0.00,0.0

In [24]:
# Compute summary statistics for fuel economy columns
summary_statistics_fuel_economy = df[['composite_city_mpg', 'composite_highway_mpg', 'composite_combined_mpg']].describe()

# Display summary statistics
print("Summary Statistics for Fuel Economy:")
print(summary_statistics_fuel_economy)

Summary Statistics for Fuel Economy:
       composite_city_mpg  composite_highway_mpg  composite_combined_mpg
count        38113.000000           38113.000000            38113.000000
mean             0.082203               0.080891                0.081311
std              2.156682               2.052187                2.097794
min              0.000000               0.000000                0.000000
25%              0.000000               0.000000                0.000000
50%              0.000000               0.000000                0.000000
75%              0.000000               0.000000                0.000000
max             97.000000              81.000000               88.000000

In [25]:
# Filter rows where fuel economy values are greater than zero
df = df[(df['composite_city_mpg'] > 0) & (df['composite_highway_mpg'] > 0) & (df['composite_combined_mpg'] > 0)]

# Reset index after filtering
df.reset_index(drop=True, inplace=True)

# Verify the changes
print(df.head())

   vehicle_id  year       make                 model            class  \
0       30980  2011  Chevrolet                  Volt     Compact Cars
1       31618  2012  Chevrolet                  Volt     Compact Cars
2       32516  2012     Fisker                 Karma  Subcompact Cars
3       32484  2012     Toyota  Prius Plug-in Hybrid     Midsize Cars
4       32655  2013  Chevrolet                  Volt     Compact Cars

               drive                      transmission  engine_index  \
0  Front-Wheel Drive                         Auto (AV)             0
1  Front-Wheel Drive                         Auto (AV)            32
2   Rear-Wheel Drive                    Automatic (A1)             1
3  Front-Wheel Drive  Automatic (variable gear ratios)            85
4  Front-Wheel Drive  Automatic (variable gear ratios)           147

   engine_cylinders  engine_displacement  ... hours_to_charge_240v  \
0               4.0                  1.4  ...                  4.0
1               4.0                  1.4  ...                  4.0
2               4.0                  2.0  ...                  6.0
3               4.0                  1.8  ...                  1.5
4               4.0                  1.4  ...                  4.0

  hours_to_charge_ac_240v composite_city_mpg  composite_highway_mpg  \
0                     0.0                 58                     62
1                     0.0                 58                     62
2                     0.0                 33                     34
3                     0.0                 59                     56
4                     0.0                 63                     61

   composite_combined_mpg  range_ft1  city_range_ft1  highway_range_ft1  \
0                      60          0             0.0                0.0
1                      60          0             0.0                0.0
2                      33          0             0.0                0.0
3                      58          0             0.0                0.0
4                      62          0             0.0                0.0

   city_range_ft2  highway_range_ft2
0         36.0000             35.000
1         36.0000             35.000
2         33.7533             32.886
3         12.1500              9.100
4         39.9196             36.302

[5 rows x 71 columns]

In [26]:
df

,vehicle_id,year,make,model,class,drive,transmission,engine_index,engine_cylinders,engine_displacement,...,hours_to_charge_240v,hours_to_charge_ac_240v,composite_city_mpg,composite_highway_mpg,composite_combined_mpg,range_ft1,city_range_ft1,highway_range_ft1,city_range_ft2,highway_range_ft2
0,30980,2011,Chevrolet,Volt,Compact Cars,Front-Wheel Drive,Auto (AV),0,4.0,1.4,...,4.0,0.0,58,62,60,0,0.0,0.0,36.0000,35.000
1,31618,2012,Chevrolet,Volt,Compact Cars,Front-Wheel Drive,Auto (AV),32,4.0,1.4,...,4.0,0.0,58,62,60,0,0.0,0.0,36.0000,35.000
2,32516,2012,Fisker,Karma,Subcompact Cars,Rear-Wheel Drive,Automatic (A1),1,4.0,2.0,...,6.0,0.0,33,34,33,0,0.0,0.0,33.7533,32.886
3,32484,2012,Toyota,Prius Plug-in Hybrid,Midsize Cars,Front-Wheel Drive,Automatic (variable gear ratios),85,4.0,1.8,...,1.5,0.0,59,56,58,0,0.0,0.0,12.1500,9.100
4,32655,2013,Chevrolet,Volt,Compact Cars,Front-Wheel Drive,Automatic (variable gear ratios),147,4.0,1.4,...,4.0,0.0,63,61,62,0,0.0,0.0,39.9196,36.302
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,38459,2017,Mercedes-Benz,GLE550e 4matic,Standard Sport Utility Vehicle 4WD,4-Wheel Drive,Automatic 7-Speed,333,6.0,3.0,...,1.9,0.0,24,27,25,0,0.0,0.0,11.9600,11.380
61,38460,2017,Mercedes-Benz,S550e,Large Cars,Rear-Wheel Drive,Automatic 7-Speed,201,6.0,3.0,...,1.9,0.0,28,36,31,0,0.0,0.0,13.0800,14.870
62,37799,2017,Porsche,Cayenne S e-Hybrid,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Auto(AM8),441,6.0,3.0,...,3.0,0.0,25,29,27,0,0.0,0.0,14.6200,13.920
63,38531,2017,Toyota,Prius Prime,Midsize Cars,Front-Wheel Drive,Automatic (variable gear ratios),108,4.0,1.8,...,2.0,0.0,83,73,78,0,0.0,0.0,27.1000,22.820
64,37703,2017,Volvo,XC90 AWD PHEV,Standard Sport Utility Vehicle 4WD,All-Wheel Drive,Automatic (S8),54,4.0,2.0,...,3.0,0.0,29,32,30,0,0.0,0.0,13.8400,13.300